# This config file for Travis CI
sudo: required

services:
  - docker

git:
  quiet: true
  submodules: false

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - ROSDEP_SKIP_KEYS="bullet3 fcl"
    - PKGS_DOWNSTREAM='tesseract_ros_examples tesseract_rosutils'
    - ROS_PARALLEL_JOBS=-j2
    - ROS_PARALLEL_TEST_JOBS=-j2

jobs:
  include:
    - os: linux
      dist: bionic
      language: minimal
      env:
      - ROS_DISTRO="melodic"
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=8
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - AFTER_SCRIPT=""
      - BADGE=clang-format
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: bionic
      language: minimal
      env:
      - ROS_DISTRO="melodic"
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - BADGE=clang-tidy
      - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_CLANG_TIDY=ON -DTESSERACT_ENABLE_TESTING=ON"
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: xenial
      language: minimal
      env:
      - ROS_DISTRO="kinetic"
      - DOCKER_IMAGE=lharmstrong/tesseract:kinetic
      - BADGE=xenial
      - CATKIN_CONFIG="--make-args CTEST_OUTPUT_ON_FAILURE=TRUE CTEST_PARALLEL_LEVEL=1"
      - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_TESTING=ON"
      - AFTER_SCRIPT='catkin build -w $CATKIN_WORKSPACE --no-deps tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_urdf tesseract_python --make-args test -j1'
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: bionic
      language: minimal
      env:
      - ROS_DISTRO="melodic"
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - BADGE=bionic
      - CATKIN_CONFIG="--make-args CTEST_OUTPUT_ON_FAILURE=TRUE CTEST_PARALLEL_LEVEL=1"
      - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_TESTING=ON"
      - AFTER_SCRIPT='catkin build -w $CATKIN_WORKSPACE --no-deps tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_urdf tesseract_python --make-args test -j1'
      cache:
        directories:
          - $HOME/.ccache

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
