name: Deploy Documentation

on:
  push:
    branches:
      - master

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v6

      - name: Build Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
            doxyfile-path: 'docs/doxygen.config'

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          publish_dir: ./docs
          destination_dir: tesseract
          keep_files: true
          external_repository: tesseract-robotics/tesseract_docs
