name: Clang-Format

on:
  push:
    branches:
      - master
      - 'dev**'
  pull_request:
    paths:
      - 'tesseract**'
      - '.github/workflows/clang_format.yml'
      - '**clang-format'
  schedule:
    - cron: '0 5 * * *'

jobs:
  clang_format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Run clang format
        run: |
          sudo apt update
          sudo apt install -y git clang-format-18
          if [ $? -ge 1 ]; then return 1; fi
          ./.run-clang-format
          if [ $? -ge 1 ]; then return 1; fi
          output=$(git diff)
          echo $output
          if [ -n "$output" ]; then exit 1; else exit 0; fi
