name: Windows-2019

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

env:
  VCPKG_PKGS: >-
    fcl bullet3[multithreading,double-precision,rtti] octomap console-bridge eigen3 yaml-cpp 
    benchmark tinyxml2 assimp orocos-kdl pcl lapack-reference boost-dll boost-filesystem boost-filesystem 
    boost-serialization boost-program-options boost-graph urdfdom ccd[double-precision]

jobs:
  windows_ci:
    name: Windows-2019
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        path: workspace/src/tesseract
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v2
      with:
        pkgs: >-
          ${{ env.VCPKG_PKGS }}
        triplet: x64-windows-release
        extra-args: --clean-after-build
    - name: install-depends
      shell: cmd
      run: |
        python -m pip install vcstool -q
        python -m pip install colcon-common-extensions -q
        python -m pip install ninja -q

    - name: configure-msvc
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: build-workspace
      working-directory: workspace
      shell: cmd
      run: |
        set PATH=%PATH%;C:/vcpkg/installed/x64-windows-release/bin
        set CMAKE_PREFIX_PATH=%GITHUB_WORKSPACE%\vcpkg\installed\x64-windows-release
        vcs import --input "${{ github.workspace }}/workspace/src/tesseract/dependencies.rosinstall" src/
        if %ERRORLEVEL% GEQ 1 exit 1
        colcon build --event-handlers console_direct+ --cmake-args -G "Ninja" -DVCPKG_TARGET_TRIPLET=x64-windows-release -DCMAKE_BUILD_TYPE=Release -DTESSERACT_ENABLE_TESTING=ON
        if %ERRORLEVEL% GEQ 1 exit 1

    - name: run-test
      working-directory: workspace
      shell: cmd
      run: |
        call ./install/setup.bat
        set PATH=%PATH%;%GITHUB_WORKSPACE%\vcpkg\installed\x64-windows-release\bin
        colcon test --event-handlers console_direct+ --return-code-on-test-failure
        if %ERRORLEVEL% GEQ 1 exit 1
        colcon test-result --verbose
        if %ERRORLEVEL% GEQ 1 exit 1
